version: '3'

services:
  postgres:
    container_name: note-bg-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: note_pg
      POSTGRES_USER: tigerprod
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
