import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from '@/components/Header';
import "@/globals.css";
import Provider from "@/app/context/client-provider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | CatsApp',
    default: 'CatsApp', // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
